#################################################################
#
# ██╗     ██╗██████╗ ██████╗  █████╗ ██████╗ ██╗███████╗███████╗
# ██║     ██║██╔══██╗██╔══██╗██╔══██╗██╔══██╗██║██╔════╝██╔════╝
# ██║     ██║██████╔╝██████╔╝███████║██████╔╝██║█████╗  ███████╗
# ██║     ██║██╔══██╗██╔══██╗██╔══██║██╔══██╗██║██╔══╝  ╚════██║
# ███████╗██║██████╔╝██║  ██║██║  ██║██║  ██║██║███████╗███████║
# ╚══════╝╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚══════╝╚══════╝
#________________________________________________________________
#==========================================================
#       Contents
#----------------------------------------------------------
#   1. Libraries List
#----------------------------------------------------------





#==========================================================
#    1. Libraries List
#----------------------------------------------------------
add_subdirectory(./rapidobj)
add_subdirectory(./stb-image)




